### ISSUE TITLE
This line has to be modified to account for new STARTING_STACK too

### ISSUE THREAD

**Issue by garyleecf** [mitpokerbots/engine-2022#9]
https://github.com/mitpokerbots/engine-2022/blob/c3286dbf228bd48bae68d73cbb45964b60b38a99/python_skeleton/skeleton/states.py#L13

**Comment by mmcmanus1** [comment]
We have changed the starting stack from 400 to 200. Please read post [@20](https://piazza.com/class/kxupvgr68k01p2?cid=20)

**Comment by shreysrins** [comment]
Closed in 15ef6821c6761c360041037e67b119668fc5da3a
